Doc/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path,re_path  
from .views import convert_images,pdf_collector_view,image_counter,pdf_counter,index,rename_images_view,start,add_logo_view,download_pdf,Requerments,to_do_delete,mark_task_completed


urlpatterns = [
    path('', start, name='start'),
    path('home/', index, name='index'),
    path('requerments/',Requerments,name='requerments'),
    path('images_to_PDFs', convert_images, name='convert_images'),
    path('pdf_collector/', pdf_collector_view, name='pdf_collector'),
    path('image_counter/', image_counter, name='image_counter'),
    path('pdf_page_counter/', pdf_counter, name='pdf_counter'),
    path('rename_images_view/', rename_images_view, name='rename_images_view'),
    path('add_logo/', add_logo_view, name='add_logo'),
    re_path(r'^download-pdf/(?P<path>.+)$', download_pdf, name='download_pdf'),
    path("delet-to-do/<int:to_do_id>",to_do_delete,name="to_do_delete"),
     path('mark-task-completed/', mark_task_completed, name='mark_task_completed'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DocBlend/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path ('',include('Doc.urls'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Doc/models.py
from django.contrib import admin
from django.db import models



class ContactMessage(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    subject = models.CharField(max_length=200)
    message = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.subject
    
class Task(models.Model):
    description = models.CharField(max_length=200)
    completed = models.BooleanField(default=False)

    def __str__(self):
        return self.description
    
admin.site.register(ContactMessage)
admin.site.register(Task)

Doc/forms.py
from django import forms
from .models import ContactMessage,Task

class LogoForm(forms.Form):
    pdf_file = forms.FileField(label='Select PDF file', help_text='Only PDF files are allowed', widget=forms.FileInput(attrs={'accept': 'application/pdf'}))
    logo = forms.ImageField(label='Select logo')

class ContactForm(forms.ModelForm):
    class Meta:
        model = ContactMessage
        fields = ['name', 'email', 'subject', 'message']
    


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['description']

Doc/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse
from django.contrib import messages
from .utils import convert_images_to_pdfs,collect_pdfs,count_images_in_folder,count_pdf_pages,rename_images,add_logo_to_pdf
from django.http import JsonResponse
import os
from .forms import LogoForm,ContactForm
from .models import Task


def start(request):
    return render(request,'start.html')

def convert_images(request):
    if request.method == 'POST':
        input_folder = request.POST.get('input_folder')
        output_folder = request.POST.get('output_folder')

        input_exists = os.path.exists(input_folder)
        output_exists = os.path.exists(output_folder)

        # Check if input and output folders exist
        if not input_exists and not output_exists:
            messages.error(request, 'Both input and output folder paths do not exist.')
        elif not input_exists:
            messages.error(request, 'Input folder path does not exist.')
        elif not output_exists:
            messages.error(request, 'Output folder path does not exist.')
            
        if not input_exists or not output_exists:
            return render(request, 'convert_images.html')

        # Perform conversion
        convert_images_to_pdfs(input_folder, output_folder)

        messages.success(request, 'Conversion successful')
        return render(request, 'convert_images.html')

    return render(request, 'convert_images.html')


def pdf_collector_view(request):
    if request.method == 'POST':
        input_folder = request.POST.get('input_folder')
        output_folder = request.POST.get('output_folder')

        # Check if input and output folders are provided
        if input_folder and output_folder:
            input_exists = os.path.exists(input_folder)
            output_exists = os.path.exists(output_folder)

            # Check if both input and output folders exist
            if input_exists and output_exists:
                # Call collect_pdfs function
                collect_pdfs(input_folder, output_folder)
                messages.success(request, 'PDFs collected successfully!')
                return redirect('pdf_collector')
            elif not input_exists and not output_exists:
                messages.error(request, f"Both input folder '{input_folder}' and output folder '{output_folder}' paths do not exist.")
            elif not input_exists:
                messages.error(request, f"The specified input folder '{input_folder}' does not exist.")
            else:
                messages.error(request, f"The specified output folder '{output_folder}' does not exist.")
        else:
            messages.error(request, 'Please provide both input and output folder paths.')

    return render(request, 'pdf_collector.html')

def image_counter(request):
    folder_path = ''
    image_count = {}
    total_images = 0
    error_message = None

    if request.method == 'POST':
        folder_path = request.POST.get('folder_path', None)
        if folder_path:
            if os.path.exists(folder_path):
                for root, dirs, files in os.walk(folder_path):
                    if files:
                        folder_images = count_images_in_folder(root)
                        image_count[root] = folder_images
                total_images = count_images_in_folder(folder_path)
            else:
                error_message = f"The specified folder '{folder_path}' does not exist."

    return render(request, 'image_counter.html', {
        'folder_path': folder_path,
        'image_count': image_count,
        'total_images': total_images,
        'error_message': error_message
    })

def pdf_counter(request):
    folder_path = ''
    pdf_info = []
    error_message = None

    if request.method == 'POST':
        folder_path = request.POST.get('folder_path', None)
        if folder_path:
            if not os.path.exists(folder_path):
                error_message = "The specified folder path does not exist."
            else:
                pdf_info = count_pdf_pages(folder_path)

    return render(request, 'pdf_counter.html', {
        'folder_path': folder_path,
        'pdf_info': pdf_info,
        'error_message': error_message
    })



def rename_images_view(request):
    if request.method == 'POST':
        source_folder = request.POST.get('source_folder')
        destination_folder = request.POST.get('destination_folder')
        image_name = request.POST.get('image_name')

        # Check if source and destination folders exist
        if not os.path.exists(source_folder) or not os.path.exists(destination_folder):
            messages.error(request, "Source or destination folder does not exist.")
            return redirect('rename_images_view')

        # Call the function to rename images
        try:
            rename_images(source_folder, destination_folder, image_name)
            messages.success(request, "Images renamed successfully.")
        except Exception as e:
            messages.error(request, f"An error occurred: {str(e)}")

        return redirect('rename_images_view')

    return render(request, 'rename_images.html')

def add_logo_view(request):
    if request.method == 'POST':
        form = LogoForm(request.POST, request.FILES)
        if form.is_valid():
            pdf_file = request.FILES['pdf_file']
            logo = request.FILES['logo']
            output_pdf_path = f'media/pdfs/output_{pdf_file.name}'

            try:
                add_logo_to_pdf(pdf_file, output_pdf_path, logo)
                messages.success(request, 'PDF with the logo has been successfully generated.')
                return render(request, 'result.html', {'output_pdf_path': output_pdf_path,'pdf_file':pdf_file,'logo':logo})
            except Exception as e:
                error_message = f"Error: {e}"
                messages.error(request, error_message)
            
            return render(request, 'add_logo.html')
    else:
        form = LogoForm()
    
    return render(request, 'add_logo.html', {'form': form})

def download_pdf(request, path):
    # Extracting file name from path
    filename = path.split('/')[-1]
    # Constructing file path without the '/add_logo' prefix
    file_path = f'media/pdfs/{filename}'
    # Open the file in binary mode
    with open(file_path, 'rb') as f:
        response = HttpResponse(f.read(), content_type='application/pdf')
        response['Content-Disposition'] = f'attachment; filename="{filename}"'
        return response
    
def Requerments(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Message sent successfully!')
            return redirect('requerments')  # Redirect to a success page
        else:
            # If form is not valid, handle the errors
            for field, errors in form.errors.items():
                for error in errors:
                    messages.error(request, f'{field}: {error}')
    else:
        form = ContactForm()
    return render(request, 'requerments.html', {'form': form})

def index(request):
    tasks=Task.objects.all()
    if request.method == 'POST':
        to_do=request.POST.get('to_do')
        task=Task.objects.create(description=to_do)
        task.save()
        

    return render(request,'index.html',{'tasks':tasks})





def to_do_delete(request,to_do_id):
    task=Task.objects.get(id=to_do_id)
    task.delete()
    return redirect(index)

def mark_task_completed(request):
    if request.method == 'POST':
        task_id = request.POST.get('task_id')
        try:
            task = Task.objects.get(id=task_id)
            task.completed = True
            task.save()
            return JsonResponse({'success': True})
        except Task.DoesNotExist:
            return JsonResponse({'success': False, 'error': 'Task not found'}, status=404)
    return JsonResponse({'success': False, 'error': 'Invalid request'}, status=400)

Doc/templates/404_error.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>404_error</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    
    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600;700&display=swap" rel="stylesheet">
    
    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    
    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body>  
    <div class="container-xxl position-relative bg-white d-flex p-0">
        <!-- Spinner Start -->
        <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <!-- Spinner End -->


        <!-- Sidebar Start -->
        <div class="sidebar pe-7 pb-3">
            <nav class="navbar bg-light navbar-light">
                <a href="{% url 'index' %}" class="navbar-brand mx-4 mb-3">
                    <h3 class="text-primary"><i class="fa fa-hashtag">Docblend</i></h3>
                </a>
                <div class="navbar-nav w-100">
                    <a href="{% url 'convert_images' %}" class="nav-item nav-link "><i class="fa fa-images me-2"></i>Images to PDFs</a>
                    <a href="{% url 'pdf_collector'%}" class="nav-item nav-link "><i class="fa fa-file-pdf me-2"></i>PDF Collector</a>
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown"><i class="far fa-file-alt me-2"></i>counter</a>
                        <div class="dropdown-menu bg-transparent border-0">
                            <a href="{% url 'image_counter'%}" class="dropdown-item">images counter</a>
                            <a href="{% url  'pdf_counter' %}" class="dropdown-item ">PDFs pages counter</a>
                        </div>
                    </div>
                    <a href="{% url 'rename_images_view'%}" class="nav-item nav-link "><i class="fa fa-edit me-2"></i>Rename Imgs</a>
                    <a href="{% url 'add_logo'%}" class="nav-item nav-link "><i class="fa fa-file-pdf me-2"></i>Pdf on logo</a>
                </div>
            </nav>
        </div>
        <!-- Sidebar End -->

        <div class="content">
            <!-- Navbar Start -->
            <nav class="navbar navbar-expand bg-light navbar-light sticky-top px-4 py-1">
                <a href="{% url 'index' %}" class="navbar-brand d-flex d-lg-none me-4">
                    <h2 class="text-primary mb-0"><i class="fa fa-hashtag"></i></h2>
                </a>
                <a href="#" class="sidebar-toggler flex-shrink-0">
                    <i class="fa fa-bars"></i>
                </a>
            </nav>
            <!-- Navbar End -->
            <!-- 404 Start -->
            <div class="container-fluid pt-4 px-4">
                <div class="row vh-100 bg-light rounded align-items-center justify-content-center mx-0">
                    <div class="col-md-6 text-center p-4">
                        <i class="bi bi-exclamation-triangle display-1 text-primary"></i>
                        <h1 class="display-1 fw-bold">404</h1>
                        <h1 class="mb-4">Page Not Found</h1>
                        <p class="mb-4">We’re sorry, the page you have looked for does not exist in our website!
                            Maybe go to our home page or try to use a search?</p>
                        <a class="btn btn-primary rounded-pill py-3 px-5" href="{{% url 'index.html'%}}">Go Back To Home</a>
                    </div>
                </div>
            </div>
            <!-- 404 End -->
        </div>
    </div>
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
<!-- Template Javascript -->
<script src="{% static 'js/main.js'%}"></script>
</body>
</html>

Doc/templates/Start.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Intro Animation</title>
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Comforter&display=swap">
  <style>
    :root {
      --primary: #009CFF;
      --light: #191C24;
      --dark: #F3F6F9;
      --screenCoeff: calc(1vw + 1vh);
      --bgColor: var(--dark);
      --fontColor: var(--light);
      --shadowColor: 0 0 0.3em var(--light);
      --glowColor: var(--primary);
    }

    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }

    body {
      font-family: "Comforter", cursive;
      background-color: var(--bgColor);
      font-size: calc(var(--screenCoeff) * 7);
      overflow: hidden;
    }

    .container {
      position: absolute;
      top: 50%;
      left: 50%;
      transform: translate(-50%, -50%);
      color: var(--fontColor);
    }

    #glowing_text {
      text-wrap: nowrap;
      text-overflow: clip;
    }

    #glowing_text {
      position: relative;
    }
  </style>
</head>
<body>
  <div class="container">
    <p id="glowing_text">#DocBleand</p>
  </div>

  <script>
    const glowingText = (() => {
      const textElement = document.getElementById('glowing_text');
      let coloredText;
      let index = 0;
 
      const startGlowing = () => {
        setInterval(() => {
          const letters = textElement.textContent.split('');
          if (letters[index] == ' ') {
            index++;
          }
          letters[
            index
          ] = `<span style="color: var(--glowColor); text-shadow: var(--shadowColor);">${letters[index]}</span>`;
          coloredText = letters.join('');
          textElement.innerHTML = coloredText;
          index = (index + 1) % letters.length;
        }, 200);
      };

      return startGlowing;
    })();

    window.addEventListener('load', () => {
      setTimeout(() => {
        window.location.href = "{% url 'index'%}"; // Replace with your website URL
      }, 2200); // 5 seconds delay
      glowingText();
    }, false);
  </script>
</body>
</html>

Doc/templates/add_logo.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Imgs_to_PDFs</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    
    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600;700&display=swap" rel="stylesheet">
    
    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    
    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body>  
    <div class="container-xxl position-relative bg-white d-flex p-0">
        <!-- Spinner Start -->
        <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <!-- Spinner End -->


        <!-- Sidebar Start -->
        <div class="sidebar pe-7 pb-3">
            <nav class="navbar bg-light navbar-light">
                <a href="{% url 'index' %}" class="navbar-brand mx-4 mb-3">
                    <h3 class="text-primary"><i class="fa fa-hashtag">Docblend</i></h3>
                </a>
                <div class="navbar-nav w-100">
                    <a href="{% url 'convert_images' %}" class="nav-item nav-link "><i class="fa fa-images me-2"></i>Images to PDFs</a>
                    <a href="{% url 'pdf_collector'%}" class="nav-item nav-link "><i class="fa fa-file-pdf me-2"></i>PDF Collector</a>
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown"><i class="far fa-file-alt me-2"></i>counter</a>
                        <div class="dropdown-menu bg-transparent border-0">
                            <a href="{% url 'image_counter'%}" class="dropdown-item">images counter</a>
                            <a href="{% url  'pdf_counter' %}" class="dropdown-item ">PDFs pages counter</a>
                        </div>
                    </div>
                    <a href="{% url 'rename_images_view'%}" class="nav-item nav-link "><i class="fa fa-edit me-2"></i>Rename Imgs</a>
                    <a href="{% url 'add_logo'%}" class="nav-item nav-link active "><i class="fa fa-file-pdf me-2"></i>Pdf on logo</a>
                </div>
            </nav>
        </div>
        <!-- Sidebar End -->

        <div class="content">
            <!-- Navbar Start -->
            <nav class="navbar navbar-expand bg-light navbar-light sticky-top px-4 py-1">
                <a href="{% url 'index' %}" class="navbar-brand d-flex d-lg-none me-4">
                    <h2 class="text-primary mb-0"><i class="fa fa-hashtag"></i></h2>
                </a>
                <a href="#" class="sidebar-toggler flex-shrink-0">
                    <i class="fa fa-bars"></i>
                </a>
                <a id="Requirement" href="{% url 'requerments'%}" class="btn btn-primary ms-auto"> other Requirement</a>
            </nav>
            <!-- Navbar End -->
            <div class="container mt-5">
                <div class="row justify-content-center">
                    <div class="col-md-8 col-lg-6">
                        <p style="color:red">*we can't remove the background form logo so that you must use the <a href="https://www.remove.bg/">'remover.bg'</a> website or etc.</p>
                        <div class="card">
                            <div class="card-body">
                                <h2 class="card-title text-center mb-4">Images to PDFs Converter</h2>
                                <form method="post" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <label for="id_pdf_file">Select PDF file:</label>
                                        {{ form.pdf_file }}
                                    </div>
                                    <br>
                                    <div class="form-group">
                                        <label for="id_logo">Select logo:</label>
                                        {{ form.logo }}
                                    </div>
                                    <br>
                                    <div class="text-center">
                                        <button type="submit" class="btn btn-primary btn-block">Submit</button>
                                    </div>
                                </form>
                                <div class="progress mt-3" style="display: none;">
                                    <div id="progress-bar" class="progress-bar" role="progressbar" style="width: 0%;" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                                <div id="progress-text" class="text-center mt-2" style="display: none;"></div>
                                {% if messages %}
                                    {% for message in messages %}
                                        {% if message.tags == 'error' %}
                                            <div class="alert alert-danger mt-3" role="alert">{{ message }}</div>
                                        {% elif message.tags == 'success' %}
                                            <div class="alert alert-success mt-3" role="alert">{{ message }}</div>
                                        {% endif %}
                                    {% endfor %}
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            
                
            </div>
            <!-- Content End -->
            
    
            <!-- Back to Top -->
            <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
    </div>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Template Javascript -->
    <script src="{% static 'js/main.js'%}"></script>
</body>
</html>

Doc/templates/result.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Imgs_to_PDFs</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    
    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600;700&display=swap" rel="stylesheet">
    
    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    
    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body>  
    <div class="container-xxl position-relative bg-white d-flex p-0">
        <!-- Spinner Start -->
        <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <!-- Spinner End -->


        <!-- Sidebar Start -->
        <div class="sidebar pe-7 pb-3">
            <nav class="navbar bg-light navbar-light">
                <a href="{% url 'index' %}" class="navbar-brand mx-4 mb-3">
                    <h3 class="text-primary"><i class="fa fa-hashtag">Docblend</i></h3>
                </a>
                <div class="navbar-nav w-100">
                    <a href="{% url 'convert_images' %}" class="nav-item nav-link "><i class="fa fa-images me-2"></i>Images to PDFs</a>
                    <a href="{% url 'pdf_collector'%}" class="nav-item nav-link "><i class="fa fa-file-pdf me-2"></i>PDF Collector</a>
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown"><i class="far fa-file-alt me-2"></i>counter</a>
                        <div class="dropdown-menu bg-transparent border-0">
                            <a href="{% url 'image_counter'%}" class="dropdown-item">images counter</a>
                            <a href="{% url  'pdf_counter' %}" class="dropdown-item ">PDFs pages counter</a>
                        </div>
                    </div>
                    <a href="{% url 'rename_images_view'%}" class="nav-item nav-link "><i class="fa fa-edit me-2"></i>Rename Imgs</a>
                    <a href="{% url 'add_logo'%}" class="nav-item nav-link active "><i class="fa fa-file-pdf me-2"></i>Pdf on logo</a>
                </div>
            </nav>
        </div>
        <!-- Sidebar End -->

        <div class="content">
            <!-- Navbar Start -->
            <nav class="navbar navbar-expand bg-light navbar-light sticky-top px-4 py-1">
                <a href="{% url 'index' %}" class="navbar-brand d-flex d-lg-none me-4">
                    <h2 class="text-primary mb-0"><i class="fa fa-hashtag"></i></h2>
                </a>
                <a href="#" class="sidebar-toggler flex-shrink-0">
                    <i class="fa fa-bars"></i>
                </a>
                <a id="Requirement" href="{% url 'requerments'%}" class="btn btn-primary ms-auto">Other Requirement</a>
            </nav>
            <!-- Navbar End -->
            <div class="container mt-5">
                <div class="row justify-content-center">
                    <div class="col-md-8 col-lg-6">
                        <div class="card">
                            <div class="card-body">
                                <h2 class="card-title text-center mb-4"> Download </h2>
                                <form method="post" enctype="multipart/form-data">
                                    
                                    <div class="form-group">
                                        <label for="id_pdf_file">Select PDF file:</label>
                                        {{ pdf_file }}
                                    </div>
                                    <br>
                                    <div class="form-group">
                                        <label for="id_logo">Select logo:</label>
                                        {{ logo }}
                                    </div>
                                    <br>
                                    <div class="text-center">
                                        <a href="{% url 'download_pdf' output_pdf_path %}" class="btn btn-primary" download>Download PDF</a>
                                    </div>
                                </form>
                                <div class="progress mt-3" style="display: none;">
                                    <div id="progress-bar" class="progress-bar" role="progressbar" style="width: 0%;" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                                <div id="progress-text" class="text-center mt-2" style="display: none;"></div>
                                {% if messages %}
                                    {% for message in messages %}
                                        {% if message.tags == 'error' %}
                                            <div class="alert alert-danger mt-3" role="alert">{{ message }}</div>
                                        {% elif message.tags == 'success' %}
                                            <div class="alert alert-success mt-3" role="alert">{{ message }}</div>
                                        {% endif %}
                                    {% endfor %}
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
                <br><br><br>
                <div class="text-primary">
                    <a href="{% url 'add_logo' %}" class="btn btn-primary">Back</a>
                </div>    
            </div>
        </div>
        
        <!-- Content End -->


        <!-- Back to Top -->
        <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
</div>
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
<!-- Template Javascript -->
<script src="{% static 'js/main.js'%}"></script>
</body>
</html>